Sodexi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/accounts/login/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('appSodexi.urls')),
]

appSodexi/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from .views.calculatrice_views import calculateur_tarif
from .views.home_view import home
from .views.iata_views import iata_upload_form
from .views.profil_views import profil
from .views.tarif_views import tarif_upload_form
from .views.visualiser_cyd40 import visualiser_cyd40
from .views.cyd_views import upload_file_view
from .views.cyd_views import generate_pdf_view
urlpatterns = [
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=
                                                                                reverse_lazy('appSodexi:password_reset_complete')), name="password_reset_confirm"),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url='done', html_email_template_name=
    'registration/password_reset_email.html'), name='password_change'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', home, name='home'),
    path('visualiser_cyd40/', visualiser_cyd40, name='visualiser_cyd40'),
    path('profil/', profil, name='profil'),


    path('admin-csv/appSodexi/iata/import-csv/', iata_upload_form, name='iata_upload_form'),
    path('admin-csv/appSodexi/tarif/import-csv/', tarif_upload_form, name='tarif_upload_form'),

    path('calculatrice/', calculateur_tarif, name='calculatrice'),

    path('upload/', upload_file_view, name='import_cyd40'),
    path('generate_pdf/', generate_pdf_view, name='visualiser_cyd_40'),

]

appSodexi/models/cydtraitement_models.py
from django.db import models
class Cyd(models.Model):
    code_app = models.CharField(max_length=5)
    code_carte = models.CharField(max_length=2)
    num_cpt_urn_collectif = models.CharField(max_length=9)
    iata_orig = models.CharField(max_length=5)
    iata_dest = models.CharField(max_length=5)
    code_cca = models.CharField(max_length=1)
    cie_lta = models.CharField(max_length=3)
    num_lta = models.CharField(max_length=8)
    code_double = models.CharField(max_length=1)
    date_emission = models.CharField(max_length=8)
    unite_poids = models.CharField(max_length=1)
    pd_brut = models.CharField(max_length=7)
    pd_taxable = models.CharField(max_length=7)
    typ = models.CharField(max_length=1)
    mnt_htfac = models.CharField(max_length=15)
    cf1 = models.CharField(max_length=3)
    mf1 = models.CharField(max_length=15)
    cf2 = models.CharField(max_length=3)
    mf2 = models.CharField(max_length=15)
    cf3 = models.CharField(max_length=3)
    mf3 = models.CharField(max_length=15)
    cf4 = models.CharField(max_length=3)
    mf4 = models.CharField(max_length=15)
    cf5 = models.CharField(max_length=3)
    mf5 = models.CharField(max_length=15)
    filler = models.CharField(max_length=1)
    cmf = models.CharField(max_length=15)
    monnaie_fac = models.CharField(max_length=3)
    nb_dec_fac = models.CharField(max_length=1)
    code_service = models.CharField(max_length=2)
    code_tva = models.CharField(max_length=1)
    mode_paiement = models.CharField(max_length=2)
    mnt_compt = models.CharField(max_length=15)
    monnaie_compt = models.CharField(max_length=3)
    nb_dec_compt = models.CharField(max_length=1)
    num_cpt_urn_individuel = models.CharField(max_length=7)
    n_facture_af = models.CharField(max_length=10)

class TXTFile(models.Model):
    file = models.FileField(upload_to='media/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file.name

appSodexi/models/iata_model.py
from django.db import models


class Iata(models.Model):
    iata_pays = models.CharField(max_length=2)
    iata_escale = models.CharField(max_length=3)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.iata_pays} -> {self.iata_escale}"


class IataCSVFile(models.Model):
    file = models.FileField(upload_to='csv_filesiata/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file.name

appSodexi/models/zonnetarif_model.py
from django.db import models


class Tarif(models.Model):
    origine = models.CharField(max_length=3)
    destination = models.CharField(max_length=3)
    minimum = models.IntegerField()
    convention = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.origine} -> {self.destination}"


class CSVFile(models.Model):
    file = models.FileField(upload_to='csv_files/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file.name

appSodexi/forms/calculatrice.py
from django import forms
from ..models import Tarif

class TarifCalculatorForm(forms.Form):
    origine = forms.ChoiceField(choices=[])
    destination = forms.ChoiceField(choices=[])
    poids_kg = forms.IntegerField(label='Poids en kg')
    cout_estime = forms.DecimalField(label='Coût estimé', max_digits=10, decimal_places=2, required=False)
    cout_cession = forms.DecimalField(label='Coût de cession', max_digits=10, decimal_places=2, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        origines = Tarif.objects.values_list('origine', flat=True).distinct().order_by('origine')
        self.fields['origine'].choices = [(origine, origine) for origine in origines]

        destinations = Tarif.objects.values_list('destination', flat=True).distinct().order_by('destination')
        self.fields['destination'].choices = [(destination, destination) for destination in destinations]

    def clean(self):
        cleaned_data = super().clean()
        origine = cleaned_data.get('origine')
        destination = cleaned_data.get('destination')
        poids_kg = cleaned_data.get('poids_kg')

        if origine and destination and poids_kg is not None:
            try:
                tarif_info = Tarif.objects.get(origine=origine, destination=destination)
                if poids_kg < tarif_info.minimum:
                    self.add_error('poids_kg', f"Le poids minimum requis est {tarif_info.minimum} kg")
                else:
                    cout_estime = poids_kg * tarif_info.convention
                    cleaned_data['cout_estime'] = cout_estime
            except Tarif.DoesNotExist:
                self.add_error('origine', "Aucun tarif trouvé pour ce routing")

        return cleaned_data

    def calculate_cout_cession(self):
        origine = self.cleaned_data.get('origine')
        destination = self.cleaned_data.get('destination')
        poids_kg = self.cleaned_data.get('poids_kg')

        if origine and destination and poids_kg is not None:
            try:
                tarif_info = Tarif.objects.get(origine=origine, destination=destination)
                cout_convention = poids_kg * tarif_info.convention
                cout_cession = cout_convention + (poids_kg * 0.069)
                return cout_cession
            except Tarif.DoesNotExist:
                self.add_error('origine', "Aucun tarif trouvé pour ce routing")
                return None

appSodexi/forms/csv_uploadform.py
from django import forms


class CSVUploadForm(forms.Form):
    csv_file = forms.FileField(label='Fichier CSV pour Tarif')

appSodexi/forms/customPasswordResetForm.py
from django import forms
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.models import User


class CustomPasswordResetForm(SetPasswordForm):
    email = forms.EmailField(label="Email", max_length=254)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("Aucun utilisateur n'est associé à cet email.")
        return email

appSodexi/forms/cyd_form.py
from django import forms


class UploadFileForm(forms.Form):
    document = forms.FileField(label='Fichier TXT pour CYD40')

appSodexi/forms/iataCSVUploadForm.py
from django import forms


class IataCSVUploadForm(forms.Form):
    csv_file = forms.FileField(label='Fichier CSV pour Iata')

appSodexi/views/calculatrice_views.py
from django.shortcuts import render
from ..forms.calculatrice import TarifCalculatorForm
from ..models import Tarif

def calculateur_tarif(request):
    form = TarifCalculatorForm(request.POST or None)
    cout_estime = None
    cout_cession = None
    tarif_info = None

    if request.method == 'POST' and form.is_valid():
        if 'calculate_convention' in request.POST:
            origine = form.cleaned_data['origine']
            destination = form.cleaned_data['destination']
            poids_kg = form.cleaned_data['poids_kg']

            try:
                tarif_info = Tarif.objects.get(origine=origine, destination=destination)
                if poids_kg < tarif_info.minimum:
                    form.add_error('poids_kg', f"Le poids minimum requis est {tarif_info.minimum} kg")
                else:
                    cout_estime = poids_kg * tarif_info.convention
            except Tarif.DoesNotExist:
                form.add_error(None, "Aucun tarif trouvé pour cette origine et destination.")
        elif 'calculate_cession' in request.POST:
            cout_cession = form.calculate_cout_cession()

    return render(request, 'calculatrice.html', {
        'form': form,
        'cout_estime': cout_estime,
        'cout_cession': cout_cession,
        'tarif_info': tarif_info,
    })

appSodexi/views/cyd_views.py
from django.shortcuts import render
from django.http import HttpResponse
from ..models.cydtraitement_models import Cyd
from ..utils import parse_file, generate_pdf
import io
from django.conf import settings
import os

def upload_file_view(request):
    if request.method == 'POST':
        uploaded_file = request.FILES['document']
        file_path = os.path.join(settings.MEDIA_ROOT, uploaded_file.name)
        with open(file_path, 'wb+') as destination:
            for chunk in uploaded_file.chunks():
                destination.write(chunk)
        parse_file(file_path)
        return HttpResponse("Fichier analysé et données enregistrées avec succès")
    return render(request, 'import_cyd40.html')

def generate_pdf_view(request):
    cyd_objects = Cyd.objects.all()
    buffer = io.BytesIO()
    generate_pdf(cyd_objects, buffer)
    buffer.seek(0)

    response = HttpResponse(buffer, content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename="rapport_vente.pdf"'
    return response

appSodexi/views/home_view.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    return render(request, 'home.html')

appSodexi/views/iata_views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from ..forms.iataCSVUploadForm import IataCSVUploadForm
from ..models import Iata
import csv

@login_required
def iata_upload_form(request):
    if request.method == 'POST':
        form = IataCSVUploadForm(request.POST, request.FILES)
        if form.is_valid():
            csv_file = request.FILES['csv_file']
            decoded_file = csv_file.read().decode('utf-8').splitlines()
            reader = csv.DictReader(decoded_file, delimiter=';')
            for row in reader:
                iata_pays = row['Iata Pays']
                iata_escale = row['Iata Escale']
                Iata.objects.create(
                    iata_pays=iata_pays,
                    iata_escale=iata_escale
                )
            messages.success(request, "Le fichier CSV pour Iata a été importé avec succès.")
            return redirect('admin:appSodexi_iata_changelist')
    else:
        form = IataCSVUploadForm()

    return render(request,dict(form=form))

appSodexi/views/pages_views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def pages(request):
    return render(request, 'pages.html')

appSodexi/views/profil_views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def profil(request):
    return render(request, 'profil.html')

appSodexi/views/tarif_views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from ..forms.csv_uploadform import CSVUploadForm
from ..models import Tarif
import csv

@login_required
def tarif_upload_form(request):
    if request.method == 'POST':
        form = CSVUploadForm(request.POST, request.FILES)
        if form.is_valid():
            csv_file = request.FILES['csv_file']
            decoded_file = csv_file.read().decode('utf-8').splitlines()
            reader = csv.DictReader(decoded_file, delimiter=';')
            for row in reader:
                origine = row['Orig']
                destination = row['Dest']
                try:
                    minimum = int(row['MIN'])
                    convention = float(row['CONV'].replace(',', '.'))
                except ValueError as e:

                    messages.warning(request, f"Il y a eu une erreur lors de la conversion des données: {str(e)}")
                    continue

                Tarif.objects.update_or_create(
                    origine=origine,
                    destination=destination,
                    defaults={'minimum': minimum, 'convention': convention}
                )

            messages.success(request, "Le fichier CSV pour Tarif a été importé avec succès.")
            return redirect('admin:appSodexi_tarif_changelist')
    else:
        form = CSVUploadForm()

    return render(request,dict(form=form))

appSodexi/views/utilities_views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def utilities(request):
    return render(request, 'utilities.html')

appSodexi/views/visualiser_cyd40.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def visualiser_cyd40(request):
    return render(request, 'visualiser_cyd40.html')

appSodexi/templates/calculatrice.html
{% extends 'home.html' %}

{% block title %}
Calculateur de Tarif
{% endblock %}

{% block main_content %}

<div class="d-flex align-items-center justify-content-center" style="min-height: 100vh;">
    <div class="container-lg">
        <div class="card shadow p-4">
            <h1 class="text-center mb-4">Calculateur de Tarif</h1>
            <form method="post" action="{% url 'calculatrice' %}" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="row g-3">
                    <div class="col-md-3">
                        <label for="id_origine" class="form-label">Origine :</label>
                    </div>
                    <div class="col-md-9">
                        {{ form.origine }}
                        <div class="invalid-feedback">
                            {{ form.origine.errors }}
                        </div>
                    </div>
                </div>
                <div class="row g-3 mt-3">
                    <div class="col-md-3">
                        <label for="id_destination" class="form-label">Destination :</label>
                    </div>
                    <div class="col-md-9">
                        {{ form.destination }}
                        <div class="invalid-feedback">
                            {{ form.destination.errors }}
                        </div>
                    </div>
                </div>
                <div class="row g-3 mt-3">
                    <div class="col-md-3">
                        <label for="id_poids_kg" class="form-label">Poids en kg :</label>
                    </div>
                    <div class="col-md-9">
                        {{ form.poids_kg }}
                        <div class="invalid-feedback">
                            {{ form.poids_kg.errors }}
                        </div>
                    </div>
                </div>
                <div class="d-grid gap-2 mt-4">
                    <button type="submit" name="calculate_convention" class="btn btn-primary">Calculer Convention</button>
                    <button type="submit" name="calculate_cession" class="btn btn-secondary">Calculer Cession</button>
                </div>
            </form>

            {% if tarif_info %}
            <div id="tarif_info" class="mt-5">
                <h2>Informations sur le tarif :</h2>
                <p>Origine : {{ tarif_info.origine }}</p>
                <p>Destination : {{ tarif_info.destination }}</p>
                <p>Minimum : {{ tarif_info.minimum }} kg</p>
                <p>Convention : {{ tarif_info.convention }}</p>
            </div>
            {% endif %}

            {% if cout_estime %}
            <div id="cout_estime" class="mt-4">
                <h2>Coût estimé :</h2>
                <p>{{ form.cleaned_data.poids_kg }} kg coûteront {{ cout_estime }} €</p>
            </div>
            {% endif %}

            {% if cout_cession %}
            <div id="cout_cession" class="mt-4">
                <h2>Coût de cession :</h2>
                <p>{{ form.cleaned_data.poids_kg }} kg coûteront {{ cout_cession }} €</p>
            </div>
            {% endif %}

            {% if form.errors %}
            <div id="form_errors" class="mt-5">
                <p class="text-danger">{{ form.errors }}</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

appSodexi/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="../../../" />
    <meta charset="utf-8" />
    <meta name="description" content="Description here" />
    <meta name="keywords" content="Keywords here" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta property="og:locale" content="en_US" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Title here" />
    <meta property="og:url" content="https://example.com" />
    <meta property="og:site_name" content="Site Name" />
    <link rel="canonical" href="http://example.com" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700" />
    <link href="{% static 'assets/css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
    <script>
        var defaultThemeMode = "light";
        var themeMode;
        if (document.documentElement) {
            if (document.documentElement.hasAttribute("data-bs-theme-mode")) {
                themeMode = document.documentElement.getAttribute("data-bs-theme-mode");
            } else {
                if (localStorage.getItem("data-bs-theme") !== null) {
                    themeMode = localStorage.getItem("data-bs-theme");
                } else {
                    themeMode = defaultThemeMode;
                }
            }
            if (themeMode === "system") {
                themeMode = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
            }
            document.documentElement.setAttribute("data-bs-theme", themeMode);
        }
    </script>
</head>
<body id="kt_body" class="header-fixed header-tablet-and-mobile-fixed toolbar-enabled toolbar-fixed aside-enabled aside-fixed">
<script>
    if (window.top != window.self) {
        window.top.location.replace(window.self.location.href);
    }
</script>
<div class="d-flex flex-column flex-root">
    <div class="page d-flex flex-row flex-column-fluid">
        <!--begin::Aside-->
        <div id="kt_aside" class="aside overflow-visible pb-5 pt-5 pt-lg-0" data-kt-drawer="true" data-kt-drawer-name="aside" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '300px'}" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_aside_mobile_toggle">
            <div class="aside-logo py-8" id="kt_aside_logo">
                <img alt="Logo" src="{% static 'assets/media/auth/imgsodexi2.png' %}" class="h-50px logo" />
            </div>

            <div class="aside-menu flex-column-fluid" id="kt_aside_menu">
                <div class="menu menu-column menu-title-gray-700 menu-state-title-primary menu-state-icon-primary menu-state-bullet-primary menu-arrow-gray-500 fw-semibold" id="#kt_aside_menu" data-kt-menu="true">
                    <div data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="right-start" class="menu-item {% if request.path == '/home/' %}here show{% endif %} py-2">
                        <a href="{% url 'home' %}" class="menu-link menu-center">
                                <span class="menu-icon me-0">
                                    <i class="ki-outline ki-home-2 fs-2x"></i>
                                </span>
                            <span class="menu-title">Home</span>
                        </a>
                    </div>
                    <div data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="right-start" class="menu-item {% if request.path == '/import_cyd40/' %}here show{% endif %} py-2">
                        <a href="{% url 'import_cyd40' %}" class="menu-link menu-center">
                                <span class="menu-icon me-0">
                                    <i class="ki-outline ki-notification-status fs-2x"></i>
                                </span>
                            <span class="menu-title">Importer CYD 40</span>
                        </a>
                    </div>
                    <div data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="right-start" class="menu-item {% if request.path == '/visualiser_cyd40/' %}here show{% endif %} py-2">
                        <a href="{% url 'visualiser_cyd40' %}" class="menu-link menu-center">
                                <span class="menu-icon me-0">
                                    <i class="ki-outline ki-abstract-35 fs-2x"></i>
                                </span>
                            <span class="menu-title">Visualiser CYD 40</span>
                        </a>
                    </div>
                    <div data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="right-start" class="menu-item {% if request.path == '/calculatrice/' %}here show{% endif %} py-2">
                        <a href="{% url 'calculatrice' %}" class="menu-link menu-center">
                                <span class="menu-icon me-0">
                                    <i class="ki-outline ki-abstract-35 fs-2x"></i>
                                </span>
                            <span class="menu-title">Calculatrice</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!--end::Aside-->
        <div class="d-flex flex-column flex-row-fluid">
            <div class="header py-4">
                <div class="container-fluid d-flex align-items-center justify-content-between">
                    <div class="d-flex justify-content-center flex-grow-1">
                        <h1 class="page-title d-flex align-items-center text-dark fw-bolder my-3 fs-1">
                            {% block title %}
                            Home
                            {% endblock %}
                        </h1>
                    </div>
                    <div class="d-flex align-items-center">
                        <div class="d-flex align-items-center ms-1 ms-lg-3" id="kt_header_user_menu_toggle">
                            <div class="cursor-pointer symbol symbol-30px symbol-md-40px" data-kt-menu-trigger="click" data-kt-menu-attach="parent" data-kt-menu-placement="bottom-end">
                                <img src="{% static 'assets/media/auth/img2.png' %}" alt="image" />
                            </div>
                            <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg menu-state-color fw-semibold py-4 fs-6 w-275px" data-kt-menu="true">
                                <div class="menu-item px-5">
                                    <form action="{% url 'profil' %}" method="get" style="display:inline;">
                                        <button type="submit" class="menu-link px-5 btn btn-link" style="text-decoration:none; padding:0; border:none; background:none;">Mon Profil</button>
                                    </form>
                                </div>
                                <div class="menu-item px-5">
                                    <form action="{% url 'logout' %}" method="post" style="display:inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="menu-link px-5 btn btn-link" style="text-decoration:none; padding:0; border:none; background:none;">Déconnexion</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
                <div class="container-xxl" id="kt_content_container">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>


    </div>
</div>
{% block main_content %}

<div class="d-flex align-items-center justify-content-center" style="min-height: 100vh; background-color: #f8f9fa;">
    <div class="container-lg">
        <div class="card shadow p-4">
            <div class="text-center mb-4">
                <img alt="Logo" src="{% static 'assets/media/auth/imgsodexi2.png' %}" class="h-50px logo mb-3"/>
                <h1>Bienvenue sur Fénix</h1>
                <p class="lead">L'outil développé par Sodexi pour gérer l'importation des fichiers CYD 40</p>
            </div>
            <div class="text-center mb-4">
                <h2>Fonctionnalités du Dashboard</h2>
                <ul class="list-unstyled">
                    <li class="mb-2"><h4>Importer le fichier CYD40</h4></li>
                    <li class="mb-2"><h4>Visualiser le fichier traité CYD40</h4></li>
                    <li class="mb-2"><h4>Calculer le coût d'une Convention ou d'une Cession avec les conditions de poids et de convention exactes</h4></li>
                </ul>
            </div>
            <div class="text-center mb-4">
                <h2>Informations Techniques</h2>
                <ul class="list-unstyled">
                    <li class="mb-2"><h4>L'import de données se fait directement dans l'admin, permettant d'importer un fichier Excel en CSV avec le séparateur : point-virgule.</h4></li>
                    <li class="mb-2"><h4>En cas de problème, veuillez faire un Kamino.</h4></li>
                </ul>
            </div>
            <div id="tarif-info" class="mt-5 text-center">
                <p class="text-danger">{{ form.errors }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<script>var hostUrl = "{% static 'assets/' %}";</script>
<script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
<script src="{% static 'assets/js/scripts.bundle.js' %}"></script>
<script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>
<script src="{% static 'assets/plugins/custom/vis-timeline/vis-timeline.bundle.js' %}"></script>
<script src="{% static 'assets/js/widgets.bundle.js' %}"></script>
<script src="{% static 'assets/js/custom/widgets.js' %}"></script>
<script src="{% static 'assets/js/custom/apps/chat/chat.js' %}"></script>
<script src="{% static 'assets/js/custom/utilities/modals/upgrade-plan.js' %}"></script>
<script src="{% static 'assets/js/custom/utilities/modals/create-campaign.js' %}"></script>
<script src="{% static 'assets/js/custom/utilities/modals/create-app.js' %}"></script>
<script src="{% static 'assets/js/custom/utilities/modals/users-search.js' %}"></script>

</body>
</html>

appSodexi/templates/import_cyd40.html
{% extends 'home.html' %}

{% block title %}
Importer CYD40
{% endblock %}

{% block main_content %}
<div class="d-flex align-items-center justify-content-center" style="min-height: 100vh;">
    <div class="container-lg">
        <div class="card shadow p-4">
            <h1 class="text-center mb-4">Importer CYD40</h1>
            <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_document" class="form-label">Sélectionnez le fichier CYD40 en format TXT:</label>
                    <input type="file" name="document" id="id_document" class="form-control" required>
                    <div class="invalid-feedback">
                        Veuillez sélectionner un fichier.
                    </div>
                </div>
                <div class="d-grid gap-2 mt-4">
                    <button type="submit" class="btn btn-primary">Télécharger</button>
                </div>
            </form>
            {% if messages %}
            <div class="mt-4">
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

appSodexi/templates/visualiser_cyd40.html
{% extends 'home.html' %}

{% block content %}
{% block title %}
Visualiser CYD40
{% endblock %}

{% endblock %}
{% block main_content %}

{% endblock %}